[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "Monospace"

[font.italic]
family = "Monospace"

[font.normal]
family = "Monospace"

[window]
opacity = 0.8
